name: keyword-enrichment-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - openpyxl
  - scikit-learn
  - pip
  - pip:
      - gprofiler-official
